# Generated by Django 5.2.13 on 2026-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_backfill_account_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=50),
        ),
    ]
