# Generated by Django 5.2.13 on 2026-04-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_manager_warehouse'),
        ('users', '0006_convert_admin_roles_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
    ]
