# Generated by Django 5.2.13 on 2026-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
    ]
