# Generated by Django 5.2.13 on 2026-04-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_remove_discount_end_date_remove_discount_start_date'),
        ('stores', '0002_remove_store_manager_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
